MarketInstrumentsService:
  Db:
    DataConnectionString:
      settings-key: MarketInstrumentsService-DataConnectionString
      types:
        - AzureTableStorage

    LogsConnectionString:
      settings-key: MarketInstrumentsService-LogsConnectionString
      types:
        - AzureTableStorage

SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
        - AzureTableStorage
    QueueName:
      settings-key: SlackQueueName

MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl